# fly.toml app configuration file generated for traffic-recorder on 2024-11-27T11:15:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'traffic-recorder'
primary_region = 'lhr'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[processes]
  # The command below is used to launch a Rails server; be sure to
  # replace with the command you're using to launch your server.
  web = "bin/rails s"
  cron = "supercronic config/crontab"


[[services]]
  processes = ["web"]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false
    [services.http_checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
